# Generated by Django 4.2.2 on 2023-11-27 14:41

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads_and_tenders', '0004_tender_datepublished'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_type', models.SmallIntegerField(choices=[(1, 'Private Company (PTY) LTD'), (2, 'Public Company (LTD)'), (3, 'Sole Proprietorship'), (4, 'Non-Profit Company (NPC)'), (5, 'Freelancer'), (6, 'Partnership'), (7, 'Personal Liability Company Inc.')])),
                ('name', models.CharField(max_length=300)),
                ('reg_num', models.CharField(blank=True, max_length=35)),
                ('address', ckeditor.fields.RichTextField()),
                ('contact_num', models.CharField(max_length=35)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('business_categories', models.ManyToManyField(blank=True, to='leads_and_tenders.category')),
                ('business_keywords', models.ManyToManyField(blank=True, to='leads_and_tenders.keywords')),
                ('contact_persons', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('provinces', models.ManyToManyField(blank=True, to='leads_and_tenders.province')),
            ],
            options={
                'verbose_name_plural': 'Service Providers',
                'ordering': ['name'],
            },
        ),
    ]
