# Generated by Django 4.2.2 on 2023-12-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0003_serviceprovider_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SP_Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_keyword', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Service Provider Unique Keywords',
                'ordering': ['sp_keyword'],
            },
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='sp_keywords',
            field=models.ManyToManyField(blank=True, to='service_provider.sp_keyword'),
        ),
    ]
