# Generated by Django 4.2.2 on 2023-12-18 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service_provider', '0004_sp_keyword_serviceprovider_sp_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_provider', to=settings.AUTH_USER_MODEL),
        ),
    ]
