# Generated by Django 4.2.2 on 2023-12-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_and_tenders', '0005_sp_and_tender'),
        ('service_provider', '0007_alter_serviceprovider_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='assigned_tenders',
            field=models.ManyToManyField(through='leads_and_tenders.SP_And_Tender', to='leads_and_tenders.tender'),
        ),
    ]
