# Generated by Django 4.2.2 on 2023-12-23 06:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_plans', '0001_initial'),
        ('service_provider', '0009_alter_serviceprovider_assigned_tenders'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SP_And_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.SmallIntegerField(choices=[(1, 'active'), (2, 'expired'), (3, 'cancelled'), (4, 'awaiting payment confirmation')])),
                ('pymnt_ref', models.CharField(max_length=10)),
                ('duration', models.SmallIntegerField(default=12)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_providers', to='pricing_plans.pricingplan')),
                ('sp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_providers', to='service_provider.serviceprovider')),
            ],
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='chosen_plan',
            field=models.ManyToManyField(blank=True, through='service_provider.SP_And_Plan', to='pricing_plans.pricingplan'),
        ),
    ]
