# Generated by Django 4.2.2 on 2023-12-23 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0010_serviceprovider_active_sp_and_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='active',
        ),
    ]
