# Generated by Django 4.2.2 on 2023-12-24 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_plans', '0001_initial'),
        ('service_provider', '0011_remove_serviceprovider_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sp_and_plan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_plans', to='pricing_plans.pricingplan'),
        ),
    ]
