# Generated by Django 4.2.2 on 2023-12-26 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_plans', '0001_initial'),
        ('service_provider', '0012_alter_sp_and_plan_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='chosen_plan',
            new_name='historical_plan',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='active_plan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_provider', to='pricing_plans.pricingplan'),
        ),
    ]
