# Generated by Django 4.2.2 on 2023-12-26 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_plans', '0001_initial'),
        ('service_provider', '0014_alter_serviceprovider_active_plan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SP_And_Plan',
            new_name='PlanSubscription',
        ),
    ]
