# Generated by Django 4.2.2 on 2023-12-26 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0015_rename_sp_and_plan_plansubscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='historical_plan',
            new_name='chosen_plan',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='active_plan',
        ),
    ]
