# Generated by Django 4.2.2 on 2023-12-26 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0016_rename_historical_plan_serviceprovider_chosen_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plansubscription',
            name='duration',
        ),
    ]
