# Generated by Django 4.2.2 on 2023-12-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0017_remove_plansubscription_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plansubscription',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'active'), (2, 'expired'), (3, 'cancelled'), (4, 'awaiting payment confirmation')], default=1),
        ),
    ]
