# Generated by Django 4.2.2 on 2023-12-27 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_plans', '0001_initial'),
        ('service_provider', '0018_alter_plansubscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plansubscription',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sp_plans', to='pricing_plans.pricingplan'),
        ),
        migrations.AlterField(
            model_name='plansubscription',
            name='sp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_providers', to='service_provider.serviceprovider'),
        ),
    ]
