# Generated by Django 4.2.2 on 2024-01-06 08:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0020_alter_plansubscription_pymnt_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_num', models.CharField(max_length=50)),
                ('invoice_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('vat_percentage', models.IntegerField(default=15)),
                ('paid', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service_provider.plansubscription')),
                ('sp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sp_invoices', to='service_provider.serviceprovider')),
            ],
            options={
                'verbose_name_plural': 'Invoices',
            },
        ),
    ]
