# Generated by Django 4.2.2 on 2024-01-06 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0021_invoices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invoices',
            new_name='Invoice',
        ),
    ]
