# Generated by Django 4.2.2 on 2024-01-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0022_rename_invoices_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_num',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
