# Generated by Django 4.2.2 on 2024-01-06 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0023_alter_invoice_invoice_num'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
