# Generated by Django 4.2.2 on 2024-01-07 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0024_delete_invoice'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_provider.plansubscription'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat_percentage',
            field=models.IntegerField(blank=True, default=15),
        ),
    ]
