"""
Django settings for saleads project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-021^khia=)v(n6p-lr955vatikes3n0b--mx9h4lfls!c8j*$%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ckeditor',
    'user_accounts',
    'leads_and_tenders',
    'pricing_plans',
    'homepage',
    'about_us',
    'contact_us',
    'dashboard',
    'companies',
    'formtools',
    'service_provider',
    'invoices',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'saleads.middleware.LoginRequiredMiddleware',
]

ROOT_URLCONF = 'saleads.urls'
AUTH_USER_MODEL = 'user_accounts.CustomUser'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['saleads/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'leads_and_tenders.context_processors.retrieve_tenders',
                'invoices.context_processors.unpaid_invoice',
            ],
        },
    },
]

WSGI_APPLICATION = 'saleads.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'saleads_db',
        'USER': 'postgres',
        'PASSWORD': 'ayaman',
        'HOST': 'localhost',
        'PORT': '5432',
    },
    'tw': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'tenderwiz_db',
        'USER': 'postgres',
        'PASSWORD': 'ayaman',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        "OPTIONS": {
            "min_length": 9,
        },
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LOGIN_EXEMPT_URLS = (
    r'^$',
    r'^admin/',
    r'^tenders/',
    r'^articles/',
    r'^contact-us/',
    r'^pricing-plans/',
    r'^user-accounts/logout_success/$',
    r'^user-accounts/register/$',
    r'^user-accounts/auth/$',
    r'^user-accounts/password_reset/$',
    r'^user-accounts/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    r'^user-accounts/register/(?P<pk>\d+)/$',
    r'^user-accounts/password_reset/done/$',
    r'^user-accounts/reset/done/$',
    r'^user-accounts/auto_complete_search/$',
    r'^user-accounts/registration_success/$',
    r'^user-accounts/payment_success/$',
    r'^user-accounts/payment_cancelled/$',
    r'^user-accounts/invoice/(?P<inv_id>\d+)/$',
    r'^province/(?P<province_pk>\d+)/$',
    r'^privacy_policy/$',
    r'^termsAndConditions/$',
    r'^about-us/$',
)


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATIC_URL = 'static/'

STATICFILES_DIRS = (os.path.join(BASE_DIR, '../static'),)


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'static/Media')

LOGIN_REDIRECT_URL = '/dashboard/'
LOGIN_URL = '/user-accounts/login/'
LOGOUT_REDIRECT_URL = '/user-accounts/login/'


GOOGLE_RECAPTCHA_SECRET_KEY = os.environ.get('RECAPTCHA_SECRET_KEY')


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_PASSWORD')
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'SA Leads <ayatech.co@gmail.com>'


AWS_STORAGE_BUCKET_NAME = 'saleads' #os.environ.get('SALEADS_BUCKET_NAME')
AWS_S3_REGION_NAME = 'eu-west-2'   #'us-east-2'
AWS_ACCESS_KEY_ID = os.environ.get('SALEADS_AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('SALEADS_AWS_SECRET_ACCESS_KEY')

# Tell django-storages the domain to use to refer to static files.
AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None


# Tell the staticfiles app to use S3Boto3 storage when writing the collected static files (when
# you run `collectstatic`).

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'      #this line enables files to be served from aws s3

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'   

STATICFILES_LOCATION = 'static'         

# STATIC_URL = 'https://{}/'.format(AWS_S3_CUSTOM_DOMAIN)       #uncomment this line to enable serving from aws s3
#
MEDIAFILES_LOCATION = 'media'  
MEDIA_URL = 'htts://{}/{}/'.format(AWS_S3_CUSTOM_DOMAIN, MEDIAFILES_LOCATION)    

AWS_S3_OBJECT_PARAMETERS = {
    'Expires': 'Thu, 31 Dec 2099 20:00:00 GMT',
    'CacheControl': 'max-age=94608000',
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MERCHANT_ID = os.environ.get('PAYFAST_MERCHANT_ID')
MERCHANT_KEY = os.environ.get('PAYFAST_MERCHANT_KEY')
