# Generated by Django 4.2.2 on 2023-12-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='provinces_num',
            field=models.SmallIntegerField(null=True),
        ),
    ]
