# Generated by Django 4.2.2 on 2023-11-07 15:52

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leads_and_tenders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyersName', models.CharField(blank=True, max_length=100, null=True)),
                ('summary', models.TextField()),
                ('refNum', models.CharField(max_length=100)),
                ('issueDate', models.DateTimeField(blank=True, null=True)),
                ('closingDate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('siteInspectionDate', models.DateTimeField(blank=True, null=True)),
                ('siteInspection', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('enquiries', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('tender_docs', ckeditor.fields.RichTextField(blank=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('assigned_keywords', models.ManyToManyField(blank=True, to='leads_and_tenders.keywords')),
                ('tenderCategory', models.ManyToManyField(to='leads_and_tenders.category')),
                ('tenderProvince', models.ManyToManyField(to='leads_and_tenders.province')),
            ],
            options={
                'ordering': ['-closingDate'],
            },
        ),
    ]
