# Generated by Django 4.2.2 on 2023-11-07 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads_and_tenders', '0002_tender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tender',
            old_name='siteInspection',
            new_name='siteInspectionAddress',
        ),
    ]
