# Generated by Django 4.2.2 on 2023-12-22 16:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0007_alter_serviceprovider_user'),
        ('leads_and_tenders', '0004_tender_datepublished'),
    ]

    operations = [
        migrations.CreateModel(
            name='SP_And_Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.BooleanField(default=False)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_provider.serviceprovider')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads_and_tenders.tender')),
            ],
        ),
    ]
