# Generated by Django 4.2.2 on 2023-12-26 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0017_remove_plansubscription_duration'),
        ('leads_and_tenders', '0005_sp_and_tender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SP_And_Tender',
            new_name='SP_Tender',
        ),
    ]
