# Generated by Django 4.2.2 on 2023-07-04 08:48

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads_and_tenders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('reg_num', models.CharField(blank=True, max_length=35)),
                ('address', ckeditor.fields.RichTextField()),
                ('contact_num', models.CharField(max_length=35)),
                ('admins', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, to='leads_and_tenders.category')),
                ('keywords', models.ManyToManyField(blank=True, to='leads_and_tenders.keywords')),
                ('provinces', models.ManyToManyField(blank=True, to='leads_and_tenders.province')),
            ],
            options={
                'verbose_name_plural': 'Registered Companies',
                'ordering': ['name'],
            },
        ),
    ]
